spring:
  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all

    consumer:
      group-id: java-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: latest
    topics:
      user: "user"
      employee: "employee"

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true